name: Terragrunt CI/CD

permissions:
  id-token: write
  contents: read

on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - qa
          - uat
          - prod

      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - apply
          - destroy

      confirm:
        description: "Type YES to confirm destroy (only for destroy)"
        required: false

jobs:

  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.0/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::273721849976:role/JenkinsRole

      - name: Terragrunt Plan (QA)
        run: |
          cd live/qa
          terragrunt run-all plan --terragrunt-non-interactive

  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    # This enables environment-based protection (for PROD)
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.0/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::273721849976:role/JenkinsRole

      - name: Run Terragrunt Action
        run: |
          cd live/${{ github.event.inputs.environment }}

          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Action: ${{ github.event.inputs.action }}"

          # Block PROD destroy (safety)
          if [ "${{ github.event.inputs.environment }}" = "prod" ] && [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            echo " Destroy not allowed in PROD environment"
            exit 1
          fi

          # Require confirmation for destroy
          if [ "${{ github.event.inputs.action }}" = "destroy" ] && [ "${{ github.event.inputs.confirm }}" != "YES" ]; then
            echo "Please type YES in confirm field to destroy"
            exit 1
          fi

          # Apply or Destroy
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terragrunt run-all apply -auto-approve --terragrunt-non-interactive
          else
            terragrunt run-all destroy -auto-approve --terragrunt-non-interactive
          fi
