name: Terragrunt CI/CD

on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - qa
          - uat
          - prod

jobs:

  # -------------------------
  # PLAN (ONLY QA ON PR)
  # -------------------------
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.0/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::273721849976:role/JenkinsRole

      - name: Plan QA
        run: |
          cd live/qa
          terragrunt run-all plan


  # -------------------------
  # APPLY (MANUAL PER ENV)
  # -------------------------
  apply:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.0/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::273721849976:role/JenkinsRole

      - name: Apply Selected Environment
        run: |
          cd live/${{ github.event.inputs.environment }}
          terragrunt run-all apply -auto-approve
